### ISSUE TITLE
Name?

### ISSUE THREAD

**Issue by metasoarous** [denistakeda/re-posh#1]
@denistakeda Nicely done!

Just a minor suggestion; While this project is still new, you _might_ want to shop around for other names. R has a core data.frame datastructure, which is quite a different beast, and it might be better not to make it look like you were trying to draw comparisons with it. That being said, it should be rather obvious to most folks familiar with Re-frame/DataScript why you chose the name, and naming things is hard (re-naming them all the more so). So do what you will. But I thought I'd let you know.

**Comment by denistakeda** [comment]
@metasoarous Thank you for the suggestion. I'll think about name.

**Comment by mikepence** [comment]
posh-frame? re-posh?

**Comment by metasoarous** [comment]
I like re-posh!

**Comment by denistakeda** [comment]
re-posh sounds good. Will fix it

**Comment by denistakeda** [comment]
Renamed to re-posh

**Comment by metasoarous** [comment]
Woohoo! Cheers!

**Comment by jamesnyika** [comment]
so this is how it got its name ....hmmmm
