### ISSUE TITLE
Support combined pull and query in a subscription

### ISSUE THREAD

**Issue by sdaros** [denistakeda/re-posh#13]
It would be really handy to be able to combine a pull and query in a subscription like you can in datascript. Assuming you want to retrieve all entity attributes for a particular product containing the unique attribute `:inv/sku`, it could look something like this:

```clojure
(re-posh/reg-pull-sub
 :item-by-sku
 (fn [ds [_ sku]]
   (datascript.core/pull '[*] (datascript.core/q '[:find ?e
                                                   :in $ ?sku
                                                   :where
                                                   [?e :inv/sku ?sku]] ds) ds)))
```

**Comment by eoliphan** [comment]
In the meantime, might be nice to have a note or 2 in the README regarding this, and perhaps any other DS features that aren't supported.

**Comment by denistakeda** [comment]
@eoliphan for now you can combine pull and query subscriptions inside the component
```clojure
(let [id      (subscribe [:query-sub])
         item (subscribe [:pull-sub  @id])])
```

**Comment by eoliphan** [comment]
Hi @denistakeda, yeah that's the pattern I've adopted in the meantime..

**Comment by rafd** [comment]
I've hacked together the following:

```clojure

(defn reg-pull-sub
  [sub-name query-pattern pull-pattern]
  (reg-sub-raw sub-name
    (fn [_ [_ & args]]
      (r/reaction
        ; result should be: id, nil, [id ...] or []
        (let [result (apply p/q query-pattern @store args)]
          (cond
            (vector? @result) ; [id ...] or []
            (->> @result
              (map (fn [id]
                     @(p/pull @store pull-pattern id)))
              doall)

            (some? @result) ; id
            @(p/pull @store pull-pattern @result)

            :else ; nil
            nil))))))

(reg-pull-sub :country
  '[:find ?e .
    :in $ ?id
    :where [?e :country/id ?id]]
  '[*])

(reg-pull-sub :countries
  '[:find [?e ...]
    :where [?e :country/id _]]
  '[*])
```

Am I doing something horrendous?

2018-04-15: Edited example code to fix a few bugs I found

**Comment by denistakeda** [comment]
@rafd Looks good, but it breaks the API. I would add the two options for this function, for one argument and for two:
```clojure
(defn reg-pull-sub
  ([sub-name pull-pattern]
   (reg-sub-row sub-name
       (fn [_ [_ id]]
          (p/pull @store pattern id))))
  ([sub-name query-pattern pull-pattern]
  (reg-sub-raw sub-name
    (fn [_ [_ & args]]
      ; result should be: id, nil, [id id ...] or []
      (let [result (apply p/q query-pattern @store args)]
        (cond
          (vector? @result) ; [id id ...] or []
          (->> @result
               (map (fn [id]
                      @(p/pull @store pull-pattern id)))
               r/reaction)

          (some? @result) ; id
          (p/pull @store pull-pattern @result)

          :else ; nil
          result))))))
```

Would you mind to create PR or I can do it myself later?

Also, I was thinking of creating a new function with API similar to re-frame [reg-sub](https://github.com/Day8/re-frame/blob/cf44443d0e2fc5009677e8082c3a6657b8a64e0c/src/re_frame/subs.cljc#L200)

**Comment by denistakeda** [comment]
[reg-sub](url)

**Comment by denistakeda** [comment]
@sdaros @eoliphan @rafd could you please have a look at #21 
It significantly improves the subscription API and resolves the problem discussed in this issue
