### ISSUE TITLE
Todo Example does not to work

### ISSUE THREAD

**Issue by orolle** [denistakeda/re-posh#15]
I tried the example of the commit ad8bf4e. I get some compiler warnings that `create-task-panel` is not defined. I declared them. Then after running figwheel without warnings, I get the todos app shown but I cannot add one by entering text in the text input.

I added some test code to strike out done tasks when they are check. re-posh handles this as expected.
```
(defn task-list-item [id]
  (let [task (re-frame/subscribe [:task id])]
    (fn []
      [:div {:class-name "task-list-item"}
       [:input {:type "checkbox"
                :checked (:task/done? @task)
                :on-change #(re-frame/dispatch [:task/set-status (:db/id @task) (not (:task/done? @task))])}]
       [:span (if (:task/done? @task)
                  [:del (:task/title @task)]
                  (:task/title @task))
                  ]])))
```

**Comment by denistakeda** [comment]
@orolle You are right, the task creation button is missed. Will fix it soon.
