### ISSUE TITLE
Resetting the db inside the conn doesn't trigger an update

### ISSUE THREAD

**Issue by Folcon** [denistakeda/re-posh#19]
So I've got the database defined as:
```clojure
(defonce conn (d/create-conn schema))
(connect! conn)
```

When I reset the `conn`
```clojure
(defn reset-conn! [db]
  (reset! conn db))
```

My subscriptions don't update.
```clojure
(re-posh/reg-query-sub
  :log/entries
  '[:find  [?log-id ...]
    :where [?log-id :type :log/entry]])
```

At the moment I'm resetting the `conn` in a normal event.
```clojure
(re-frame/reg-event-db
  :reset-system
  (fn [db [_]]
    (let [_ (println (pr-str @db/conn) (pr-str (d/empty-db db/schema)))
           _ (db/reset-conn! (d/empty-db db/schema))
           ]
      {:active-panel :home-panel})))
```

I've also tried calling
```clojure
(connect! conn)
```

Am I missing a step or is this a bug?

**Comment by denistakeda** [comment]
@Folcon to reset database you can use datascript reset-conn!
```clojure
(datascript.core/reset-conn! connection new-database)
```
Here is an example: https://github.com/denistakeda/balance/blob/master/src/balance/boot.cljs
That time `re-posh` had nave `data-frame`, but api is still the same

**Comment by Folcon** [comment]
@denistakeda Thank you.
