### ISSUE TITLE
Feature Request : Datalog Rules

### ISSUE THREAD

**Issue by CharlesHD** [denistakeda/re-posh#23]
So I'd like to be able to use datalog rules in re-posh, but i'm not sure it is actually possible. 
Some ideas : 
+ having a `(reg-query-sub key query rules)` version of `(reg-query-sub key query)`
+ having a `{:type :query :query q :variables [...] :rules [...]}` format for `reg-sub`

I may do a PR about that if you're okay with this.

**Comment by denistakeda** [comment]
@CharlesHD yeah, missed this part. PRs are very much appreciated
