### ISSUE TITLE
Wording clarification

### ISSUE THREAD

**Issue by piotr-yuxuan** [denistakeda/re-posh#25]
Hello,
Thanks for this awesome project, I'm quite thrilled to refactor the code of a pet project so I can use it. However, would you mind some clarification? The readme states 

> `re-posh` is a ClojureScript library

but all the code is in `cljc` files. Do you see any reason it could smoothly work, or not work, on a clj runtime? As far as I know, you use `datascript` which is also written in `cljc` files so it _should_ work but I'd like to know the viewpoint of the maintainer.

Thanks in advance!

**Comment by denistakeda** [comment]
Hello.

I've never tested it in Clojure environment (and never thought anybody needs it), but theoretically it should work. It depends heavily on 3 libraries: `datascript`, `posh` and `re-frame` and all three use `cljc`.

So, I hope it should just work out of the box, but if not feel free to create an issue.

**Comment by piotr-yuxuan** [comment]
OK, thanks a lot for your kind reply. I'll let you know if I have any trouble with this promising library :-)
