### ISSUE TITLE
How do you handle pull-many?

### ISSUE THREAD

**Issue by jpmonettas** [denistakeda/re-posh#26]
First of all, thanks for the tool! I'm looking forward using it in a new app but trying to figure out how
to solve some common situations first.

Lets say I need to pull some attributes for a bunch of tasks-ids.
Would be nice to have something like : 

```clojure
(re-posh/reg-sub
 ::task-ids
 (fn [_ _]
   {:type :query
    :query '[:find  [?tid ...]
             :where [?tid :app/type :type/task]]}))

(re-posh/reg-sub
 ::task
 :<- [::task-ids]
 (fn [ids _]
   {:type    :pull-many
    :pattern '[:db/id :task/done? :task/title]
    :ids      id}))
```

Is there another way to solve this situations with re-posh now?

Thank!

**Comment by denistakeda** [comment]
I'm planning to introduce `pull-many` soon. Currently, you can pull each on component level.

**Comment by zachcp** [comment]
Hi @denistakeda ,  

Thanks again for your excellent library.   I would also find `pull-many` to be a useful feature - especially for populating tables.

zach cp

**Comment by jamesnyika** [comment]
Definitely hoping to benefit from this.  hoping to be able to do this:

````
(re-posh/reg-sub
 :lookup
 (fn [_ [_{:keys [lookupname]}]]
  
   ;;
   {:type    :pull-many
    :pattern '[*]
    :id       [:category/name "Customer Type"]})) 

````
Where anything that references this unique value "Customer Type" will be pulled back. 

However, I know that datascript supports back references. is there a way to use that OR the existing pull to get back all values of type "customer type" from this data and get:

### Desired result
```` 
[{:db/id 1 :lookup/name "Company" :lookup/value :company}
  {:db/id 2 :lookup/name "Person" :lookup/value :person}
  {:db/id 3 :lookup/name "Group" :lookup/value :group}]

````

### Schema 
```` 
  :category/name          {:db/doc    "A category discrimiator to tie up with lookup values"
                                        :db/unique :db.unique/identity}
  :lookup/name            {:db/doc    "A lookup value"
                                       :db/unique :db.unique/identity}
  :lookup/value           {:db/doc "A value associate with this name"}
  :lookup/type            {:db/doc       "Type of lookup value"
                           :db/valueType :db.type/ref
                           }
````

### Data
````
            {:category/name "Customer Type"}
;;-------------------------------------------------------
            {:lookup/name "Company"
             :lookup/value :company
             :lookup/type [:category/name "Customer Type"]}
            {:lookup/name "Person"
             :lookup/value :person
             :lookup/type [:category/name "Customer Type"]}
            {:lookup/name "Group"
             :lookup/value :group
             :lookup/type [:category/name "Customer Type"]}

````

**Comment by jamesnyika** [comment]
BTW.. this is my current working solution however @denistakeda - is there a way to do it in 1 query ?
maybe it is just my ignorance..


```` 
;; Notice : DO NOT USE re-posh reg-sub. It expects a map with either pull or query. 
;; No escape hatch.
;; use the re-frame version of the function. Reposh will fail because it does not expect the results you
;; return

(reg-sub
 :lookup
 ;; the first param is the re-frame database map NOT the re-posh datasource. You must extract.
 (fn [db [_{:keys [lookupname]}]]

   ;; perform the 2 required queries ( @denistakeda - is there a way to do it in 1 query ? ) 
          ;; IMPORTANT - you must get your actual datascript connect handle here
          ;; YOU MUST DEREF to get the contents of the atom
   (let [ds @(:re-conn db)
           ;; Query 1 - get all ids for the entities with category/name of "customer type"
           ids  (d/q '[:find [?e ...]
           :in $ ?ln
           :where
             [?a :category/name ?ln]
             [?e :lookup/type ?a]
             ] ds lookupname)
         ;; Query 2 - pull all the values for each of the many IDS. Datascript superpower!
         lvals (d/pull-many ds '[*] ids)
             ]
     ;; return the data 
     lvals
             )

))



````

**Comment by denistakeda** [comment]
Hello @jamesnyika 
This looks good, however... The problem here (and the reason why it's still not implemented) is that I want not only working solution but the performant solution. It's very easy to use pure datascript here, but if `re-posh` goes that way, it will calculate the query every time something is changed in the database, which is the show stopper if you have a lot of queries.

**Comment by jamesnyika** [comment]
@denistakeda 
I fully understand. I needed an immediate solution so I am by no means advocating that everyone follow my lead. But I hate being that guy in the forum who says he has a workaround and but does not tell 😃 

I look forward to the solution that works for the library .. and not just for me! 
🥇 for the library!

**Comment by Quezion** [comment]
@denistakeda Is the issue here the missing pull-many API in the underlying Posh library, or did you have an implementation in mind that wouldn't require it? I'd really like to use re-posh & I could try integrating the pull-many API into Posh.

(I've been trying to build my app off re-posh & hit this roadblock -- I could roll with @jamesnyika's solution for now but would eventually hit performance issues.)

**Comment by denistakeda** [comment]
Hello @Quezion 
I see two solutions here:
1) Implement this solution into a posh and then wrap it in re-posh
2) (this one I intended to implement) Wrap several posh pulls into a single reagent reaction.

**Comment by Quezion** [comment]
@denistakeda Given your response, I've made some progress on implementing `pull-many` into posh this morning. I'll continue working on this & report back early next week.

As an aside, posh has not been easy to figure out... lot of time in a step-thru debugger. I doubt my solution will be especially performant, but I'll be happy if it actually works.

**Comment by Quezion** [comment]
@denistakeda I have at least a basic pull-many reaction working (albiet not yet using DataScript's pull-many) -- if you'd like to test or build out re-posh's API, I've published it under coordinates `[org.clojars.questyarbrough/posh:0.5.8-SNAPSHOT]`.

The working tree that I'm developing is at https://github.com/Quezion/posh/tree/pull-many-support

I'll continue iterating on this SNAPSHOT version for the pull-many functionality. Note that it also includes the "vector support" changes in PR https://github.com/mpdairy/posh/pull/38 , so it's possible that there are unrelated breakages... Posh has no test suite to speak of, but I've been slowly accumulating some DataScript tests.

*EDIT: And [here's the test](https://github.com/Quezion/posh/blob/pull-many-support/test/posh/lib/datascript_test.cljc#L123) demonstrating extremely basic usage of `pull-many`

**Comment by Quezion** [comment]
I've updated Posh to use Datascsript's `pull-many` & opened a PR against the official `posh` library at https://github.com/mpdairy/posh/pull/39

I have no tests on performance & I'm sure there's optimizations to be made, but it seems functional.

I've updated `[org.clojars.questyarbrough/posh:0.5.8-SNAPSHOT]` with the changes. If you'd like (@denistakeda) I can release this under a permanent fork -- I haven't heard back from Matt Parker (mpdairy) yet & I don't know the timeline on getting these changes into the official `posh`.

Also @denistakeda -- I'll try to integrate this into re-posh tomorrow unless you'd prefer to. Barring that I can use jame's serviceable workaround, but I don't anticipate the integration being difficult so I might as well go ahead & do it 🙂

**Comment by zachcp** [comment]
this is really nice work, @Quezion.

**Comment by Quezion** [comment]
I've made a PR with re-posh pull-many support at https://github.com/denistakeda/re-posh/pull/34 . Until an official release, this functionality is available at `[org.clojars.questyarbrough/re-posh "0.3.1-SNAPSHOT"]`.

Please see the PR & its README.md for usage instructions.
