### ISSUE TITLE
Don't see updates of a datom which properties are edited

### ISSUE THREAD

**Issue by akond** [denistakeda/re-posh#31]
i use figwheel during development. naturally i make a lot of changes and every time figwheel reloads the page. when i use reframes's `reg-sub` it works fine, but when i switched to re-posh's `reg-query-sub` it seizes to update the subscription after figwheel refreshes the page. i wonder what did i do wrong?

my initial db:
```
(def initial-db
	[{:db/id     1
	  :app/route [:root]}])
```

my handler:
```
(rp/reg-event-ds
	::route
	(fn [db args]
		[[:db/add 1
		  :app/route (rest args)]]))
```

and a subscription:
```
(rp/reg-query-sub
	::route
	'[:find ?route .
	  :where [1 :app/route ?route]])
```

**Comment by denistakeda** [comment]
Hello

I recently updated the todomvc example to latest figwheel and it handles this problem. The main idea here is to use defonce with do block. Please have a look here: https://github.com/denistakeda/re-posh/blob/c390b2aaf6dafcc78d04dc4e83b04ebd64f50b5b/examples/todomvc/src/todomvc/core.cljs#L21

**Comment by akond** [comment]
Yes, this solves the problem.

**Comment by akond** [comment]
Thank you.

**Comment by jamesnyika** [comment]
@denistakeda @akond  Does this affect cases where you actually switch out the entire datascript database such as where I implement a backup-to-file strategy ? At the point that I call reset-conn! to swap in a new database read in from a transit serialization...

```` 
(d/reset-conn! db (in/fromTransitString data))

````
..I am hoping but do not see any changes in my UI fields that rely on a re-posh subscription: 

````
;; this subscription should but DOES NOT TRIGGER when I swap out the DB ..
(re-posh/reg-sub
 :data/dashboard
 ; notice for id you can use a ref-map
 (fn [_ _]
   {:type    :pull
    :pattern '[*]
    :id      [:user/email "somejoker@gmail.com"]}))

````

**Comment by denistakeda** [comment]
Hello @jamesnyika 

I don't think that THIS case causes your problem, but here are some suggestions that can make your life easier.
- Never do any writing operations to your datascript database outside your events. This can cause not updating subscriptions (as in your case).
- Database is nothing more than just a vector of datoms... the same thing as a transaction. So basically you can just transact the whole database you got from transit inside the regular event. It can look like so:
```
(re-posh/reg-event-ds
 ::reset-database
 (fn [_ [_ new-ds]]
   new-ds))
```
When executed this event just transact the whole database to the existing one. It can be used in this way:
```
(re-posh/dispatch-sync [::reset-database (in/fromTransitString data)])
```

**Comment by jamesnyika** [comment]
Appreciate it!!! Thank you.
