### ISSUE TITLE
Datascript version

### ISSUE THREAD

**Issue by rlhk** [denistakeda/re-posh#33]
https://github.com/denistakeda/re-posh/blob/c390b2aaf6dafcc78d04dc4e83b04ebd64f50b5b/project.clj#L7

Should Datascript version be updated? 
If I have the latest Datascript version in my own project dependency, which version will `re-posh` use?

**Comment by Quezion** [comment]
@rlhk I'm not sure which version will be used, but I know you can use Lein `:exclusions` to force your own explicit version.

Dependency vector  for re-posh should look like this.

```clj
[re-posh "x.x.x" :exclusions [datascript]]
```

**Comment by rlhk** [comment]
@Quezion thanks for replying. My project is using shadow-cljs instead of Leinigen.

By the way, the more important question is why re-posh's datascript version is so old?

**Comment by denistakeda** [comment]
@rlhk Hello and thank you for the issue. There is no special reason, I just haven't updated it for a long time. I'm going to update version soon, test that it works and use something like [posh](https://github.com/denistakeda/posh/blob/2291fff6515f460f633f7beb27a32eab84554a57/project.clj#L8) uses for dependencies. For now you can try to follow @Quezion suggestion.

**Comment by denistakeda** [comment]
Hello @rlhk . This issue is fixed in `v 0.3.1`. `datascript` version has been updated and `provided` scope used, which means that you should provide your own version of `datascript`.
