### ISSUE TITLE
When reg-pull-sub use the nested map , how can reactive update the relation data? 

### ISSUE THREAD

**Issue by xlisp** [denistakeda/re-posh#36]
I use the `:get-tree` get nested map tree, when i dispatch update the content, it's will reactive update frontend ui.
```clojure
(re-posh/reg-pull-sub
  :get-tree
  '[:id :content {:_parid ...}])

```
but i change the parid , by this code: 

```clojure
(re-posh/reg-event-ds
  :remove-parid
  (fn [_ [_event eid-sub eid-father]]
    [[:db/retract eid-sub :parid eid-father]]))

```
it's can not reactive update.

**Comment by xlisp** [comment]
when subscribe the `:get-tree` will get this output:

```clojure

{:db/id 4,
 :id "46376310-a7ad-11ea-9c98-fb9a71d5f3bb",
 :content "AAA",
 :_parid
 [{:db/id 2,
   :id "9b1d96ba-a7ad-11ea-8284-5b0dc85f01a8",
   :content "BBB"}
  {:db/id 3,
   :id "7ebd8192-a7ad-11ea-8385-5be8868d06cb",
   :content "CCC"}]}

```

**Comment by xlisp** [comment]
And i add new entity, it's can't reactive update :

```clojure
  (re-posh/reg-event-ds
    :add-entity-test
    (fn [ds [_ id]]
      [[:db/add 5 :content "DDD"]
       [:db/add 5 :parid 4]
       [:db/add 5 :id "7ebd8192-a7ad-11ea-8385-5be8868d06cb"]]))

```

**Comment by denistakeda** [comment]
Hello @chanshunli . Thank you for reporting this issue. I'll have a look at it a bit later

**Comment by denistakeda** [comment]
Hello @chanshunli . I investigated this problem a  little bit and have been thinking about your use case in general. I wrote an additional example to `re-posh` "how would I do this": https://github.com/denistakeda/re-posh/tree/master/examples/tree

If this won't help, could you please provide an example repository with reproduction of your case? Most likey there are some problem in `posh` library (also maintained by me), which needs deeper analysys.
