### ISSUE TITLE
How to idiomatically get value from the ds in an event handler?

### ISSUE THREAD

**Issue by zendevil** [denistakeda/re-posh#40]
Suppose I have this event handler:

```
(re-posh/reg-event-fx
   :my-event
   [(re-posh/inject-cofx :ds)] ;; inject coeffect
   (fn [{:keys [ds]} [_ id k v]] ;; ds here is the DataScript database
      {:transact [[:db/add id k v]]}))
```

In which I inject the ds coeffect. I want to know how to actually get a value out of the datastore. Do you use a datascript query like so:?
`(d/q '[:find ?foo . :where [...]])`
But this makes the event handler impure because we're using a function (d/q ) that's declared outside the scope of the event handler.
Is there a fix around this?

**Comment by denistakeda** [comment]
Hello @zendevil . Executing the function `d/q` inside the event handler is completely valid, there are no requirements that function should be defined in the scope of the event handler, but only that this function should be pure (no side-effects). And `d/q` is pure, so you can use it without any problem.
As an option you can create some sort of a wrapper, that limits what user can do, here is an example:
```clojure
(defn reg-event-with-query
  "registers the event handler of special shape
  event-name - the name of the event, keyword
  query - the datascript query
  handler - a function, that accepts the result of query execution and returns datoms for transaction"
  [event-name query handler]
  (re-posh/reg-event-fx
   event-name
   [(re-posh/inject-cofx :ds)]
   (fn [{:keys [ds]} [_ id k v]]
     {:transact (handler (d/q query ds))})))

;; example usage
(reg-event-with-query
 :my-event
 '[:find ?foo . :where [...]]
 (fn [query-resul]
   (do-something-and-return-datoms-for-transaction)))
```
